name: cbrconecta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # Our dependencies
  http: ^0.13.4
  splashscreen: 
  flutter_icons:
  path_provider: ^2.0.9
  file_picker:
  open_file:
  shared_preferences:
  archive:
  velocity_x: 
  flutter_local_notifications:
  flutter_pdfview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   
  
